### ISSUE TITLE
Updated version of Genesis Framework required

### ISSUE THREAD

**Issue by aryanrajseo** [genesisplugins/genesis-child-theme#1]
Add a warning before activating Genesis Customizer theme if updated/min. version of Genesis Framework is required. Deactivate the GC theme automatically or fail the installation if user is using older version of Genesis Framework.

Currently, the warning is in backend and makes the frontend without CSS.

source:
https://genesiscustomizer.slack.com/archives/CH45WEJUC/p1553774430002800

https://genesiscustomizer.slack.com/archives/CH45WEJUC/p1553957919070000

**Comment by genesisplugins** [comment]
Fixed in latest commit
